### ISSUE TITLE
Compile for MacOS / WinForm example

### ISSUE THREAD

**Issue by ThibaudMZN** [mikeoliphant/AudioPlugSharp#17]
Hi ! 
I just stumbled upon this repository, and it looks pretty promising !
I used to work on VST2 development with Steinberg's SDK in C++.

I was wondering, does this compile also for MacOS hosts ? 
I'm pretty unfamiliar with the VST3 specs.

On a side note, is there any example for a WinForm VST ?
And if not, could you point me to what method of your API I could use to modify a parameter from a WinForm control ?

Thanks !

**Comment by mikeoliphant** [comment]
I have not tried to get it to work in MacOS. I suspect there would be two issues. First, AudioPlugSharp uses C++/CLR for bootstrapping the managed code. This is Windows-only, so a different solution would be required for MacOS. Second, a different UI integration would be required.

As for WinForms, I do not have an example, but it should be relatively easy to do. You would need to create a WinForms context from the window pointer the VST host passes instead of a WPF context.

**Comment by ThibaudMZN** [comment]
I was suspicious about the UI integration indeed, but didn't know about C++/CLR, thanks for the clarification !

All right, thanks then, I'll try to make a simple working example in WinForms !

**Comment by mikeoliphant** [comment]
Have a look at how SharpSoundDevice  (a C# VST2 solution I used to use before I wrote AudioPlugSharp) does it:

https://github.com/ValdemarOrn/SharpSoundDevice/blob/aed15cbb5937838028cf85b3e252fc12309ed9be/SharpSoundDevice/DeviceUtilities.cs

In particular:

```
		public static void DockWinFormsPanel(System.Windows.Forms.Control panel, IntPtr vstWindow)
		{
			System.Windows.Forms.Application.EnableVisualStyles();

			panel.Top = 0;
			panel.Left = 0;

			SetParent(panel.Handle, vstWindow);
		}
```

It should be as simple as that to link up a Window Forms control with the parent window handle from the VST.

**Comment by ThibaudMZN** [comment]
Ah thanks that's a great example !
